name: Build and Test Svelte

on:
  push:
    branches:
      - develop
      - master 
jobs:
  build:
    environment:
      name: build
    runs-on: ubuntu-latest
    steps:
        - name: pulling git repo
          uses: actions/checkout@v2
        - name: Set up Node.js version
          uses: actions/setup-node@v2
          with:
            node-version: '12.x'

        - name: Install Dependencies
          run: | 
            npm install
            npm build --if-present
        
  test:
    environment: 
      name: testing
    runs-on: ubuntu-latest
    steps:
        - name: pulling git repo
          uses: actions/checkout@v2
        - name: Set up Node.js version
          uses: actions/setup-node@v2
          with:
            node-version: '12.x'

        - name: Install Dependencies
          run: npm install
        - name: Build App
          run: npm build
        - name: Tests
          run: npm test --if-present