name: Build and Test Svelte

on:
  push:
    branches:
      - develop
      - master 
jobs:
  build:
    environment:
      name: build
    runs-on: ubuntu-latest
    steps:
        - name: pulling git repo
          uses: actions/checkout@v2
        - name: Set up Node.js version
          uses: actions/setup-node@v1
          with:
            node-version: '12.x'

        - name: Install Dependencies
          run: | 
            npm install
            npm run build
            npm run test --if-present
